# FROM python:3.6.8
FROM tensorflow/tensorflow:1.14.0-py3

WORKDIR /usr/src/app

RUN apt-get update \
    && apt-get install -y \
        cmake libsm6 libxext6 libxrender-dev protobuf-compiler \
    && rm -r /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y libgl1-mesa-glx

COPY algorithm/requirements.txt algorithm/requirements.txt
COPY backend/requirements.txt backend/requirements.txt
RUN pip install --upgrade pip setuptools wheel -i https://mirrors.aliyun.com/pypi/simple/
# RUN mkdir -p ~/.pip
# COPY algorithm/pip.conf ~/.pip/pip.conf
# RUN pip config list

RUN pip install --no-cache-dir -r algorithm/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ && \
pip install --no-cache-dir -r backend/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

COPY . .

ENTRYPOINT ["python", "-m", "backend.backend"]
